### ISSUE TITLE
did a git pull from github and compiled SW - derod does not sync the NW

### ISSUE THREAD

**Issue by kroupouk666** [deroproject/dero#10]
Guys and girls,

I compiled latest greatest on github but it does not sync the NW. Is there a reason?

**Comment by Mojo-LB** [comment]
This is the old version.

The new version is available at http:://seeds.dero.io/alpha

Backwards compatibility has been dropped today.

**Comment by kroupouk666** [comment]
Why not firing up a new repo on github? It's a million times easier to get the updates via git pull? It gives version control as well....

**Comment by chron0** [comment]
ye, asking the same....and has TLS as well...

**Comment by chron0** [comment]
wat? only bins? you must be kidding

**Comment by kroupouk666** [comment]
Is it me or our issue got deleted?
 
--------- Original Message --------- Subject: Re: [deroproject/dero] did a git pull from github and compiled SW - derod does not sync the NW (#10)

**Comment by Mojo-LB** [comment]
Doesn't look like it was deleted, but not sure why I didn't get email notifications earlier.

Anyway the source will be posted in few weeks. It is currently only available through http://seeds.dero.io/alpha

Alpha7 was pushed recently, and it drops support with old Helium Hydra version. The team had to drop compatibility earlier than planned due to rising attacks and vulnerabilities in Helium Hydra.
